/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telaVisao;

//Encontrar arquivo no txt
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import javax.swing.JOptionPane;


import com.nohair.controle.ClientesControle;
import com.nohair.util.id.GeradorID;
import javax.swing.JOptionPane;
import com.nohair.modelos.Clientes;
import com.nohair.persistencia.ClientesDao;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.table.DefaultTableModel;
import com.nohair.persistencia.IClientesDao;
import com.nohair.controle.IClientesControle;
import java.io.File;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.Icon;


import javax.swing.table.TableRowSorter;
import javax.swing.text.MaskFormatter;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.JRadioButton;



public class TelaDeClientes extends javax.swing.JFrame {
                
    //Atributos 
    IClientesControle ClientesControle = new ClientesControle();
    
    //Mascaras CNPJ / CPF / ...
    private MaskFormatter CNPJMask;
    private MaskFormatter CPFMask;
    private MaskFormatter RGMask;
    private MaskFormatter NascMask;
    private MaskFormatter TelMask;
    private MaskFormatter CEPMask;

    public TelaDeClientes(){
        try{
            initComponents();
            
            ClientesDao objeto = new ClientesDao();
            objeto.ChecarTxt();
            
            // Inicializa a Mascara CNPJ / CPF / ...
            CNPJMask = new MaskFormatter("##.###.###/####-##");
            CPFMask = new MaskFormatter("###.###.###-##");
            RGMask = new MaskFormatter("#######");
            NascMask = new MaskFormatter("## / ## / ####");
            TelMask = new MaskFormatter("+## (###) # #### - ####");
            CEPMask = new MaskFormatter("## . ### - ###");
                    
                   
            // Inicializa Vazio e o cursor na posiçao 0
            Txt_NomeCompleto.setText("");
            Txt_NomeCompleto.setCaretPosition( 0 );
            Txt_ID.setText("");
            Txt_CPF.setText("");
            Txt_CPF.setCaretPosition( 0 );
            Txt_RG.setText("");
            Txt_RG.setCaretPosition( 0 );
            Txt_Data_Nasc.setText(""); 
            Txt_Data_Nasc.setCaretPosition( 0 );
            Txt_Telef.setText("");
            Txt_Telef.setCaretPosition( 0 );
            Txt_Email.setText("");
            Txt_Email.setCaretPosition( 0 );
            Txt_Endereco.setText("");
            Txt_Endereco.setCaretPosition( 0 );
            Txt_Bairro.setText("");
            Txt_Bairro.setCaretPosition( 0 );
            Txt_CEP.setText("");
            Txt_CEP.setCaretPosition( 0 );
            Txt_Cidade.setText("");
            Txt_Cidade.setCaretPosition( 0 );
            Txt_Estado.setText("");
            Txt_Estado.setCaretPosition( 0 );
            Txt_Caminho_Foto.setText("");
        
            // Campos Iniciam desativados
            Txt_NomeCompleto.setEnabled(false);
            Txt_ID.setEnabled(false);
            Txt_CPF.setEnabled(false);
            Txt_RG.setEnabled(false);
            Txt_Data_Nasc.setEnabled(false);
            Txt_Telef.setEnabled(false);
            Txt_Email.setEnabled(false);
            Txt_Endereco.setEnabled(false);
            Txt_Bairro.setEnabled(false);
            Txt_CEP.setEnabled(false);
            Txt_Cidade.setEnabled(false);
            Txt_Estado.setEnabled(false);
            Txt_Caminho_Foto.setEnabled(false);
        
            DefaultTableModel modelo = (DefaultTableModel) jTableClientes.getModel();
            jTableClientes.setRowSorter(new TableRowSorter(modelo));
        
            this.setLocationRelativeTo(null);
            
                try {
                    imprimirDadosNaGrid(ClientesControle.listagem());
                } 
                catch (Exception erro) {
                    JOptionPane.showMessageDialog(this, "Erro ao Puxar a Lista de Clientes");
                }  
        }
        catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Erro ao Inicializar","Erro",JOptionPane.ERROR);
        }   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Fundo = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButtonBuscar = new javax.swing.JButton();
        jButtonAlterar = new javax.swing.JButton();
        jButtonIncluir = new javax.swing.JButton();
        Bt_Add_Foto = new javax.swing.JButton();
        jButtonNovoCadastro = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableClientes = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        PFisica_Pjuridica = new javax.swing.JLabel();
        Txt_NomeCompleto = new javax.swing.JTextField();
        CPF_CNPJ = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Txt_Endereco = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        Txt_Bairro = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Txt_Cidade = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        Txt_Estado = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Txt_Caminho_Foto = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        Bt_P_Fisica = new javax.swing.JRadioButton();
        Bt_P_Juridica = new javax.swing.JRadioButton();
        Txt_CPF = new javax.swing.JFormattedTextField();
        Txt_Telef = new javax.swing.JFormattedTextField();
        Txt_Data_Nasc = new javax.swing.JFormattedTextField();
        Txt_CEP = new javax.swing.JFormattedTextField();
        Txt_Email = new javax.swing.JTextField();
        Txt_RG = new javax.swing.JFormattedTextField();
        Txt_ID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Area_Logo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuOpcoes = new javax.swing.JMenu();
        jMenuItemLocacao = new javax.swing.JMenuItem();
        jMenuItemCadastroDeMotorista = new javax.swing.JMenuItem();
        jMenuItemCadastroDeCategorias = new javax.swing.JMenuItem();
        jMenuItemCadastroDeAcessorios = new javax.swing.JMenuItem();
        jMenuItemCadastroVeiculo = new javax.swing.JMenuItem();
        jMenuItemCadastroDeCliente = new javax.swing.JMenuItem();
        jMenuItemCadastroDeModelo = new javax.swing.JMenuItem();
        jMenuItemCadastroDeMarca = new javax.swing.JMenuItem();
        jMenuItemTelaInicial = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jRadioButtonMenuItem2.setSelected(true);
        jRadioButtonMenuItem2.setText("jRadioButtonMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela de Cadastro de Clientes");

        jPanel1.setBackground(new java.awt.Color(0, 51, 153));

        jLabel1.setFont(new java.awt.Font("Arial", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cadastro de Clientes");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap())
        );

        Fundo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel2.setBackground(new java.awt.Color(255, 255, 153));
        jPanel2.setForeground(new java.awt.Color(255, 255, 153));

        jButtonBuscar.setText("BUSCAR");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jButtonAlterar.setText("ALTERAR");
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });

        jButtonIncluir.setText("INCLUIR");
        jButtonIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIncluirActionPerformed(evt);
            }
        });

        Bt_Add_Foto.setText("ADD FOTO");
        Bt_Add_Foto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_Add_FotoActionPerformed(evt);
            }
        });

        jButtonNovoCadastro.setText("NOVO ");
        jButtonNovoCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoCadastroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Bt_Add_Foto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonIncluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonNovoCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Bt_Add_Foto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonIncluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonNovoCadastro)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jTableClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NOME", "CPF", "RG", "DATA DE NASCIMENTO", "TELEFONE", "EMAIL", "ENDEREÇO", "BAIRRO", "CEP", "CIDADE", "ESTADO", "URL"
            }
        ));
        jTableClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableClientesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableClientes);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados de Cadastro"));

        PFisica_Pjuridica.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        PFisica_Pjuridica.setText("Nome Completo:");

        Txt_NomeCompleto.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        CPF_CNPJ.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        CPF_CNPJ.setText("CPF:");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("Identidade:");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("Data de Nascimento:");

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setText("Telefone:");

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setText("Endereço:");

        Txt_Endereco.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel13.setText("Bairro:");

        Txt_Bairro.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Txt_Bairro.setPreferredSize(new java.awt.Dimension(64, 29));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel14.setText("CEP:");

        jLabel15.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel15.setText("Cidade:");

        Txt_Cidade.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Txt_Cidade.setMinimumSize(new java.awt.Dimension(64, 29));
        Txt_Cidade.setPreferredSize(new java.awt.Dimension(64, 29));

        jLabel16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel16.setText("Estado:");

        Txt_Estado.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Txt_Estado.setPreferredSize(new java.awt.Dimension(64, 29));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Caminho da Foto:");

        Txt_Caminho_Foto.setEditable(false);
        Txt_Caminho_Foto.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel18.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel18.setText("e-mail:");

        buttonGroup1.add(Bt_P_Fisica);
        Bt_P_Fisica.setText("Pessoa Fisica");
        Bt_P_Fisica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Bt_P_FisicaMouseClicked(evt);
            }
        });

        buttonGroup1.add(Bt_P_Juridica);
        Bt_P_Juridica.setText("Pessoa Juridica");
        Bt_P_Juridica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Bt_P_JuridicaMouseClicked(evt);
            }
        });

        Txt_CPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        Txt_CPF.setMinimumSize(new java.awt.Dimension(64, 29));

        try {
            Txt_Telef.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        Txt_Telef.setMinimumSize(new java.awt.Dimension(64, 29));
        Txt_Telef.setPreferredSize(new java.awt.Dimension(96, 29));

        try {
            Txt_Data_Nasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        Txt_Data_Nasc.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Txt_Data_Nasc.setMinimumSize(new java.awt.Dimension(64, 29));

        try {
            Txt_CEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        Txt_CEP.setPreferredSize(new java.awt.Dimension(64, 29));

        Txt_Email.setPreferredSize(new java.awt.Dimension(64, 29));

        try {
            Txt_RG.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        Txt_RG.setMinimumSize(new java.awt.Dimension(64, 29));

        jLabel2.setText("ID");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Bt_P_Fisica)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Bt_P_Juridica))
                    .addComponent(Txt_Caminho_Foto, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(CPF_CNPJ)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Txt_Data_Nasc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Txt_RG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Txt_CPF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Txt_Telef, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                                    .addComponent(Txt_Email, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel12))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Txt_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addComponent(jLabel15)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(Txt_Cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(jLabel13)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Txt_Bairro, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(jLabel16)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Txt_Estado, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(jLabel14)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Txt_CEP, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addGap(58, 58, 58)
                                            .addComponent(Txt_Endereco, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(PFisica_Pjuridica)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Txt_NomeCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Txt_Bairro, Txt_CEP, Txt_Cidade, Txt_Estado});

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Txt_Email, Txt_Telef});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5))
                    .addComponent(Txt_Caminho_Foto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bt_P_Fisica)
                    .addComponent(Bt_P_Juridica))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Txt_ID)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(PFisica_Pjuridica)
                        .addComponent(Txt_NomeCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(Txt_Endereco, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Txt_CPF, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CPF_CNPJ))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(Txt_Bairro, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Txt_RG, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(Txt_CEP, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Txt_Data_Nasc, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Txt_Cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(jLabel9)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Txt_Telef, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Txt_Estado, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Txt_Email, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel18)))
                .addGap(14, 14, 14))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Txt_CPF, Txt_Data_Nasc, Txt_NomeCompleto});

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Txt_Bairro, Txt_CEP, Txt_Cidade, Txt_Endereco, Txt_Estado});

        javax.swing.GroupLayout FundoLayout = new javax.swing.GroupLayout(Fundo);
        Fundo.setLayout(FundoLayout);
        FundoLayout.setHorizontalGroup(
            FundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FundoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FundoLayout.createSequentialGroup()
                .addGroup(FundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FundoLayout.createSequentialGroup()
                        .addGap(0, 76, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE))
                    .addGroup(FundoLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(Area_Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );
        FundoLayout.setVerticalGroup(
            FundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FundoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FundoLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(Area_Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenuOpcoes.setText("Options");

        jMenuItemLocacao.setText("Locação");
        jMenuItemLocacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLocacaoActionPerformed(evt);
            }
        });
        jMenuOpcoes.add(jMenuItemLocacao);

        jMenuItemCadastroDeMotorista.setText("Cadastro de Motorista");
        jMenuItemCadastroDeMotorista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroDeMotoristaActionPerformed(evt);
            }
        });
        jMenuOpcoes.add(jMenuItemCadastroDeMotorista);

        jMenuItemCadastroDeCategorias.setText("Cadastro de Categorias");
        jMenuItemCadastroDeCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroDeCategoriasActionPerformed(evt);
            }
        });
        jMenuOpcoes.add(jMenuItemCadastroDeCategorias);

        jMenuItemCadastroDeAcessorios.setText("Cadastro de Acessorios");
        jMenuItemCadastroDeAcessorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroDeAcessoriosActionPerformed(evt);
            }
        });
        jMenuOpcoes.add(jMenuItemCadastroDeAcessorios);

        jMenuItemCadastroVeiculo.setText("Cadastro de Veículo");
        jMenuItemCadastroVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroVeiculoActionPerformed(evt);
            }
        });
        jMenuOpcoes.add(jMenuItemCadastroVeiculo);

        jMenuItemCadastroDeCliente.setText("Cadastro de Cliente");
        jMenuItemCadastroDeCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroDeClienteActionPerformed(evt);
            }
        });
        jMenuOpcoes.add(jMenuItemCadastroDeCliente);

        jMenuItemCadastroDeModelo.setText("Cadastro de Modelo");
        jMenuItemCadastroDeModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroDeModeloActionPerformed(evt);
            }
        });
        jMenuOpcoes.add(jMenuItemCadastroDeModelo);

        jMenuItemCadastroDeMarca.setText("Cadastro de Marca");
        jMenuItemCadastroDeMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroDeMarcaActionPerformed(evt);
            }
        });
        jMenuOpcoes.add(jMenuItemCadastroDeMarca);

        jMenuItemTelaInicial.setText("Tela Inicial");
        jMenuItemTelaInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTelaInicialActionPerformed(evt);
            }
        });
        jMenuOpcoes.add(jMenuItemTelaInicial);

        jMenuBar1.add(jMenuOpcoes);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(Fundo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(Fundo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void imprimirDadosNaGrid(ArrayList<Clientes> listaDeClientes){
        try {
            DefaultTableModel model =  (DefaultTableModel) jTableClientes.getModel();
            //Limpa a tabela 
            model.setNumRows(0);
            
            Iterator<Clientes> lista = listaDeClientes.iterator();
            
            while(lista.hasNext()){
                
                String[] saida= new String[13];
                
                Clientes aux = lista.next();
                saida[0]= aux.getId()+"";
                saida[1]= aux.getNomeCompleto();
                saida[2] = aux.getCPF();
                saida[3] = aux.getRG();//
                saida[4] = aux.getData_Nasc();//
                saida[5] = aux.getTelefone();//
                saida[6] = aux.getEmail();
                saida[7] = aux.getEndereco();//
                saida[8] = aux.getBairro();//
                saida[9] = aux.getCEP();//
                saida[10] = aux.getCidade();//
                saida[11] = aux.getEstado();//
                saida[12] = aux.getCaminho_Foto();
                
                model.addRow(saida);
                
            } 
        } 
        catch(Exception erro){
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }              
    }
    
    private void AtivarCampos(){
                    Txt_NomeCompleto.setEnabled(true);
                    Txt_NomeCompleto.setEnabled(true);
                    Txt_CPF.setEnabled(true);
                    Txt_RG.setEnabled(true);
                    Txt_Telef.setEnabled(true);
                    Txt_Email.setEnabled(true);
                    Txt_Endereco.setEnabled(true);
                    Txt_Bairro.setEnabled(true);
                    Txt_CEP.setEnabled(true);
                    Txt_Cidade.setEnabled(true);
                    Txt_Estado.setEnabled(true);
                    Txt_Caminho_Foto.setEnabled(true);       
    }
    
    private void DesativaCampos(){
                    Txt_NomeCompleto.setEnabled(false);
                    Txt_NomeCompleto.setEnabled(false);
                    Txt_CPF.setEnabled(false);
                    Txt_RG.setEnabled(false);
                    Txt_Telef.setEnabled(false);
                    Txt_Email.setEnabled(false);
                    Txt_Endereco.setEnabled(false);
                    Txt_Bairro.setEnabled(false);
                    Txt_CEP.setEnabled(false);
                    Txt_Cidade.setEnabled(false);
                    Txt_Estado.setEnabled(false);
                    Txt_Caminho_Foto.setEnabled(false);       
    }
    
    
    
    
    private void jButtonIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIncluirActionPerformed
                  
        try {   
 
            if(!Txt_NomeCompleto.getText().isEmpty() && !Txt_NomeCompleto.getText().matches("[a-zA-ZÀ-ÿ\\s]+")) {
                JOptionPane.showMessageDialog(null,"Nome Inválido!");
                Txt_NomeCompleto.setText("");
            } 
            if (!Txt_Cidade.getText().isEmpty() && Txt_Cidade.getText().matches(".*\\d.*")) {
                JOptionPane.showMessageDialog(null, "Nome de Cidade Inválida!");
                Txt_Cidade.setText("");
            }
            if (!Txt_Estado.getText().isEmpty() && Txt_Estado.getText().matches(".*\\d.*")) {
                JOptionPane.showMessageDialog(null, "Nome de Cidade Inválida!");
                Txt_Estado.setText("");
            }
            
            // Se tiver algum campo vazio o mesmo gerar mensagem "Para Correçao " 
            if(!Txt_NomeCompleto.getText().equals("") && !Txt_CPF.getText().equals("") && !Txt_RG.getText().equals("")
                && !Txt_Data_Nasc.getText().equals("") && !Txt_Telef.getText().equals("") && !Txt_Endereco.getText().equals("") 
                && !Txt_Bairro.getText().equals("")&& !Txt_CEP.getText().equals("") && !Txt_Cidade.getText().equals("")  
                && !Txt_Estado.getText().equals("") && !Txt_Caminho_Foto.getText().equals("") ){
         
                    //Construtor Cliente
                    Clientes objeto = new Clientes(0,Txt_NomeCompleto.getText(),Txt_CPF.getText(),Txt_RG.getText(),
                    Txt_Data_Nasc.getText(), Txt_Telef.getText(),Txt_Email.getText(),Txt_Endereco.getText(),Txt_Bairro.getText(),
                    Txt_CEP.getText(),Txt_Cidade.getText(),Txt_Estado.getText(), Txt_Caminho_Foto.getText());
            
                    ClientesControle.incluir(objeto);
            
                    // Atualiza a Grid quando Incluir
                    this.imprimirDadosNaGrid(ClientesControle.listagem());
                    
                    // Zera os Campos com Mascaras 
                    Txt_CPF.setValue(null);
                    Txt_CPF.setFormatterFactory(new DefaultFormatterFactory(CNPJMask));
                    Txt_CPF.setValue(null);
                    Txt_CPF.setFormatterFactory(new DefaultFormatterFactory(CPFMask));
                    Txt_RG.setValue(null);
                    Txt_RG.setFormatterFactory(new DefaultFormatterFactory(RGMask));
                    Txt_Data_Nasc.setValue(null);
                    Txt_Data_Nasc.setFormatterFactory(new DefaultFormatterFactory(NascMask));
                    Txt_Telef.setValue(null);
                    Txt_Telef.setFormatterFactory(new DefaultFormatterFactory(TelMask));
                    Txt_CEP.setValue(null);
                    Txt_CEP.setFormatterFactory(new DefaultFormatterFactory(CEPMask));
            
                    Txt_NomeCompleto.setText("");
                    Txt_ID.setText("");
                    Txt_Email.setText("");
                    Txt_Endereco.setText("");
                    Txt_Bairro.setText("");
                    Txt_Cidade.setText("");
                    Txt_Estado.setText("");
                    Txt_Caminho_Foto.setText("");
                    //Area_Logo.setIcon(null);  
                    
                    //Zera o JradioButton
                    buttonGroup1.clearSelection();
                    Bt_P_Fisica.setSelected(false);
                    Bt_P_Juridica.setSelected(false);
            }                
            else{
                // Se houver campo vazio no cadastro e mostrado uma mensagem !
                JOptionPane.showMessageDialog(this, "Campo Vazio");
            }    
        } 
        catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }                   
    }//GEN-LAST:event_jButtonIncluirActionPerformed

    private void Bt_Add_FotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_Add_FotoActionPerformed
        try {        
            
            JFileChooser fc = new JFileChooser();
            
            //Title da Barra de buca da Foto
            fc.setDialogTitle("Buscar Foto");
                    
            fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
            
            // Abre no diretorio especifico
            fc.setCurrentDirectory(new File ("./src/com/nohair/fotoCliente"));
            
            fc.showOpenDialog(this);
            
            File arquivo = fc.getSelectedFile();
            String nomeDoArquivo = arquivo.getPath();
            
            Txt_Caminho_Foto.setText(nomeDoArquivo);
            
            ImageIcon iconLogo = new ImageIcon(nomeDoArquivo);
            iconLogo.setImage(iconLogo.getImage().getScaledInstance(
            Area_Logo.getWidth(),Area_Logo.getHeight(),1));
            Area_Logo.setIcon(iconLogo);
        } 
        catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro);
        }
    }//GEN-LAST:event_Bt_Add_FotoActionPerformed

    private void jTableClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableClientesMouseClicked
      
      try{
        // Ao selecionar a linha da tabela, apresenta os valores no TextField
        
        if(jTableClientes.getSelectedRow() != -1){
            
            String CPFouCNPJ = jTableClientes.getValueAt(jTableClientes.getSelectedRow(),2).toString();      
            
            // Diferenciando cadastro CPF / CNPJ na Grid 
            if(CPFouCNPJ.length()==14){
                Txt_Data_Nasc.setEnabled(true); 
                Txt_RG.setEnabled(true);
                Txt_Data_Nasc.setValue(null);                
                Txt_RG.setValue(null);
                    
                //Muda o texto na Tela Pessoa Fisica / Pessoa Juridica
                PFisica_Pjuridica.setText("Nome Completo:");
                CPF_CNPJ.setText("CPF:"); 
                
                Txt_CPF.setValue(null);
                Txt_CPF.setFormatterFactory(new DefaultFormatterFactory(CPFMask));
                
                Txt_ID.setText(jTableClientes.getValueAt(jTableClientes.getSelectedRow(),0).toString());           
                Txt_NomeCompleto.setText(jTableClientes.getValueAt(jTableClientes.getSelectedRow(),1).toString());
                Txt_CPF.setText(jTableClientes.getValueAt(jTableClientes.getSelectedRow(),2).toString());                
                Txt_RG.setText(jTableClientes.getValueAt(jTableClientes.getSelectedRow(),3).toString());
                Txt_Data_Nasc.setText(jTableClientes.getValueAt(jTableClientes.getSelectedRow(),4).toString());
                Txt_Telef.setText(jTableClientes.getValueAt(jTableClientes.getSelectedRow(),5).toString());
                Txt_Email.setText(jTableClientes.getValueAt(jTableClientes.getSelectedRow(),6).toString());
                Txt_Endereco.setText(jTableClientes.getValueAt(jTableClientes.getSelectedRow(),7).toString());
                Txt_Bairro.setText(jTableClientes.getValueAt(jTableClientes.getSelectedRow(),8).toString());
                Txt_CEP.setText(jTableClientes.getValueAt(jTableClientes.getSelectedRow(),9).toString());
                Txt_Cidade.setText(jTableClientes.getValueAt(jTableClientes.getSelectedRow(),10).toString());
                Txt_Estado.setText(jTableClientes.getValueAt(jTableClientes.getSelectedRow(),11).toString());             
                Txt_Caminho_Foto.setText(jTableClientes.getValueAt(jTableClientes.getSelectedRow(),12).toString());
                
                // Apresenta a foto do cliente no Campo Logo
                String nomeArquivo = (String) this.jTableClientes.getValueAt(jTableClientes.getSelectedRow(),12);
                ImageIcon iconLogo = new ImageIcon(nomeArquivo);
                iconLogo.setImage(iconLogo.getImage().getScaledInstance(Area_Logo.getWidth(), Area_Logo.getHeight(), 1));
                Area_Logo.setIcon(iconLogo);
            }                      
            else if(CPFouCNPJ.length()==18){
                Txt_Data_Nasc.setEnabled(false);
                Txt_Data_Nasc.setValue(null);                
                Txt_RG.setEnabled(false);
                Txt_RG.setValue(null);
                   
                //Muda o texto na Tela - Pessoa Fisica / Pessoa Juridica//
                PFisica_Pjuridica.setText("Razao Social:");
                CPF_CNPJ.setText("CNPJ:"); 
                
                // Zera a Mascara e Imprime o resultado da Grid
                Txt_CPF.setValue(null);
                Txt_CPF.setFormatterFactory(new DefaultFormatterFactory(CNPJMask));
                
                Txt_ID.setText(jTableClientes.getValueAt(jTableClientes.getSelectedRow(),0).toString());           
                Txt_NomeCompleto.setText(jTableClientes.getValueAt(jTableClientes.getSelectedRow(),1).toString());
                Txt_CPF.setText(jTableClientes.getValueAt(jTableClientes.getSelectedRow(),2).toString());
                               
                Txt_Telef.setText(jTableClientes.getValueAt(jTableClientes.getSelectedRow(),5).toString());
                Txt_Email.setText(jTableClientes.getValueAt(jTableClientes.getSelectedRow(),6).toString());
                Txt_Endereco.setText(jTableClientes.getValueAt(jTableClientes.getSelectedRow(),7).toString());
                Txt_Bairro.setText(jTableClientes.getValueAt(jTableClientes.getSelectedRow(),8).toString());
                Txt_CEP.setText(jTableClientes.getValueAt(jTableClientes.getSelectedRow(),9).toString());
                Txt_Cidade.setText(jTableClientes.getValueAt(jTableClientes.getSelectedRow(),10).toString());
                Txt_Estado.setText(jTableClientes.getValueAt(jTableClientes.getSelectedRow(),11).toString());
            }                                                               
            //Buscar o caminho da foto e mostrar no LogoArea         
        }       
      }
      catch (Exception ERRO){
        JOptionPane.showMessageDialog(null, "Erro ao Selecionar a Tabela","Erro",JOptionPane.ERROR);
      }    
      
    }//GEN-LAST:event_jTableClientesMouseClicked

    private void Bt_P_JuridicaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bt_P_JuridicaMouseClicked
            try{
                if(Bt_P_Juridica.isSelected()){
                    AtivarCampos();
                    Txt_Data_Nasc.setEnabled(false);
                    Txt_RG.setEnabled(false);
                    
                    //Muda o texto na Tela Pessoa Fisica / Pessoa Juridica
                    PFisica_Pjuridica.setText("Razao Social:");
                    CPF_CNPJ.setText("CNPJ:"); 
                    JOptionPane.showMessageDialog(null, "Pessoa Juridica, Selecionada");
                    
                    // Formata a Mascara e zera o JtextFieldFormated
                    //CNPJMask = new MaskFormatter("##.###.###/####-##");    Colocado no inciar do programa 
                    Txt_CPF.setValue(null);
                    Txt_CPF.setFormatterFactory(new DefaultFormatterFactory(CNPJMask));    
                    
                    Txt_Telef.setValue(null);
                    Txt_Telef.setFormatterFactory(new DefaultFormatterFactory(TelMask));
                    Txt_CEP.setValue(null);
                    Txt_CEP.setFormatterFactory(new DefaultFormatterFactory(CEPMask));
                }
            }
            catch (Exception ERRO){
                JOptionPane.showMessageDialog(null, "Erro ao formatar campo CPF/CNPJ","Erro",JOptionPane.ERROR);
            }                       
    }//GEN-LAST:event_Bt_P_JuridicaMouseClicked

    private void Bt_P_FisicaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bt_P_FisicaMouseClicked
            try{   
                if(Bt_P_Fisica.isSelected()){
                    AtivarCampos();
                    Txt_Data_Nasc.setEnabled(true); 
                    
                    //Muda o texto na Tela Pessoa Fisica / Pessoa Juridica
                    PFisica_Pjuridica.setText("Nome Completo:");
                    CPF_CNPJ.setText("CPF:"); 
                    JOptionPane.showMessageDialog(null, "Pessoa Fisica, Selecionada");
                    
                    // Formata a Mascara e zera o JtextFieldFormated
                    // CPFMask = new MaskFormatter("###.###.###-##");        Colocado no inciar do programa     
                    Txt_CPF.setValue(null);
                    Txt_CPF.setFormatterFactory(new DefaultFormatterFactory(CPFMask));
    
                    Txt_RG.setValue(null);
                    Txt_RG.setFormatterFactory(new DefaultFormatterFactory(RGMask));
                    Txt_Data_Nasc.setValue(null);
                    Txt_Data_Nasc.setFormatterFactory(new DefaultFormatterFactory(NascMask));
                    Txt_Telef.setValue(null);
                    Txt_Telef.setFormatterFactory(new DefaultFormatterFactory(TelMask));
                    Txt_CEP.setValue(null);
                    Txt_CEP.setFormatterFactory(new DefaultFormatterFactory(CEPMask));
                }   
            }
            catch (Exception ERRO){
                JOptionPane.showMessageDialog(null, "Erro ao formatar campo CPF/CNPJ","Erro",JOptionPane.ERROR);
            }           
    }//GEN-LAST:event_Bt_P_FisicaMouseClicked

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
	try {          
            Clientes objeto = new Clientes(Integer.parseInt(Txt_ID.getText()),Txt_NomeCompleto.getText().toUpperCase(),Txt_CPF.getText(),Txt_RG.getText(),
               Txt_Data_Nasc.getText(), Txt_Telef.getText(),Txt_Email.getText(),Txt_Endereco.getText(),Txt_Bairro.getText(),
               Txt_CEP.getText(),Txt_Cidade.getText(),Txt_Estado.getText(), Txt_Caminho_Foto.getText());
            
            ClientesControle.alterar(objeto);
            
            imprimirDadosNaGrid(ClientesControle.listagem());          
        } 
        catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());          
        }
    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        try{
            for(int i = 0; i < jTableClientes.getRowCount(); i++){
                if(jTableClientes.getValueAt(i, 1).toString().toLowerCase().contains(Txt_NomeCompleto.getText().toLowerCase())){
                    jTableClientes.changeSelection(i, 0, false, false);
                }
            }
        
        }
        catch(Exception erro){
            JOptionPane.showMessageDialog(null, "Erro ao buscar","Erro",JOptionPane.ERROR);
        }
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonNovoCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoCadastroActionPerformed
        try{
            Bt_P_Juridica.setSelected(false);
            Bt_P_Fisica.setSelected(false);              
        }
        catch(Exception erro){
            JOptionPane.showMessageDialog(null, "Erro Novo Cadastro","Erro",JOptionPane.ERROR);
        }
    }//GEN-LAST:event_jButtonNovoCadastroActionPerformed

    private void jMenuItemLocacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLocacaoActionPerformed
        /*
        try {
            TelaDeLocacao telaLocacao = new TelaDeLocacao();
            telaLocacao.setLocationRelativeTo(null);
            telaLocacao.setVisible(true);
            this.setVisible(false);
            telaLocacao.setResizable(false);
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro);
        }
        */
    }//GEN-LAST:event_jMenuItemLocacaoActionPerformed

    private void jMenuItemCadastroDeMotoristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroDeMotoristaActionPerformed
        /*
        try {
            TelaCadastroMotorista telaMotorista = new TelaCadastroMotorista();
            telaMotorista.setLocationRelativeTo(null);
            telaMotorista.setVisible(true);
            this.setVisible(false);
            telaMotorista.setResizable(false);
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro);
        }
        */
    }//GEN-LAST:event_jMenuItemCadastroDeMotoristaActionPerformed

    private void jMenuItemCadastroDeCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroDeCategoriasActionPerformed
        /*
        try {

            TelaDeCategoria telaCategoria = new TelaDeCategoria();
            telaCategoria.setLocationRelativeTo(null);
            telaCategoria.setVisible(true);
            this.setVisible(false);
            telaCategoria.setResizable(false);
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro);
        }
        */
    }//GEN-LAST:event_jMenuItemCadastroDeCategoriasActionPerformed

    private void jMenuItemCadastroDeAcessoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroDeAcessoriosActionPerformed
        /*
        try {
            TelaDeAcessorios telaAcessorios = new TelaDeAcessorios();
            telaAcessorios.setLocationRelativeTo(null);
            telaAcessorios.setVisible(true);
            this.setVisible(false);
            telaAcessorios.setResizable(false);
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro);
        }
        */
    }//GEN-LAST:event_jMenuItemCadastroDeAcessoriosActionPerformed

    private void jMenuItemCadastroVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroVeiculoActionPerformed

        try {
            TelaDeVeiculos telaVeiculo = new TelaDeVeiculos();
            telaVeiculo.setLocationRelativeTo(null);
            telaVeiculo.setVisible(true);
            this.setVisible(false);
            telaVeiculo.setResizable(false);
        }
        catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro);
        }
    }//GEN-LAST:event_jMenuItemCadastroVeiculoActionPerformed

    private void jMenuItemCadastroDeClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroDeClienteActionPerformed

        try {
            TelaDeClientes cadastroCliente = new TelaDeClientes();
            cadastroCliente.setLocationRelativeTo(null);
            cadastroCliente.setVisible(true);
            this.setVisible(false);
            cadastroCliente.setResizable(false);
        }
        catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro);
        }

    }//GEN-LAST:event_jMenuItemCadastroDeClienteActionPerformed

    private void jMenuItemCadastroDeModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroDeModeloActionPerformed
        // TODO add your handling code here:
        try {
            TelaDeModelos telaModelo = new TelaDeModelos();
            telaModelo.setLocationRelativeTo(null);
            telaModelo.setVisible(true);
            this.setVisible(false);
            telaModelo.setResizable(false);
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro);
        }
    }//GEN-LAST:event_jMenuItemCadastroDeModeloActionPerformed

    private void jMenuItemCadastroDeMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroDeMarcaActionPerformed
        // TODO add your handling code here:
        try {

            TelaDeMarcas telaMarca = new TelaDeMarcas();
            telaMarca.setLocationRelativeTo(null);
            telaMarca.setVisible(true);
            this.setVisible(false);
            telaMarca.setResizable(false);
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro);
        }
    }//GEN-LAST:event_jMenuItemCadastroDeMarcaActionPerformed

    private void jMenuItemTelaInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTelaInicialActionPerformed

        try {
            telaAdminOpcoes telaInicial = new telaAdminOpcoes();
            telaInicial.setLocationRelativeTo(null);
            telaInicial.setVisible(true);
            this.setVisible(false);
            telaInicial.setResizable(false);
        }
        catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro);
        }
    }//GEN-LAST:event_jMenuItemTelaInicialActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDeClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDeClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDeClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDeClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDeClientes().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Area_Logo;
    private javax.swing.JButton Bt_Add_Foto;
    private javax.swing.JRadioButton Bt_P_Fisica;
    private javax.swing.JRadioButton Bt_P_Juridica;
    private javax.swing.JLabel CPF_CNPJ;
    private javax.swing.JPanel Fundo;
    private javax.swing.JLabel PFisica_Pjuridica;
    private javax.swing.JTextField Txt_Bairro;
    private javax.swing.JFormattedTextField Txt_CEP;
    private javax.swing.JFormattedTextField Txt_CPF;
    private javax.swing.JTextField Txt_Caminho_Foto;
    private javax.swing.JTextField Txt_Cidade;
    private javax.swing.JFormattedTextField Txt_Data_Nasc;
    private javax.swing.JTextField Txt_Email;
    private javax.swing.JTextField Txt_Endereco;
    private javax.swing.JTextField Txt_Estado;
    private javax.swing.JTextField Txt_ID;
    private javax.swing.JTextField Txt_NomeCompleto;
    private javax.swing.JFormattedTextField Txt_RG;
    private javax.swing.JFormattedTextField Txt_Telef;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonIncluir;
    private javax.swing.JButton jButtonNovoCadastro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemCadastroDeAcessorios;
    private javax.swing.JMenuItem jMenuItemCadastroDeCategorias;
    private javax.swing.JMenuItem jMenuItemCadastroDeCliente;
    private javax.swing.JMenuItem jMenuItemCadastroDeMarca;
    private javax.swing.JMenuItem jMenuItemCadastroDeModelo;
    private javax.swing.JMenuItem jMenuItemCadastroDeMotorista;
    private javax.swing.JMenuItem jMenuItemCadastroVeiculo;
    private javax.swing.JMenuItem jMenuItemLocacao;
    private javax.swing.JMenuItem jMenuItemTelaInicial;
    private javax.swing.JMenu jMenuOpcoes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableClientes;
    // End of variables declaration//GEN-END:variables
}
